//! Adapter for locale tables generated by `pure-rust-locales`.
//!
//! Each `locale_match!` call expands hundreds of dependency-owned match arms.
//! Runtime behavior is exercised by the locale tests, while this generated
//! dispatch adapter is excluded from first-party region coverage accounting.

use pure_rust_locales::{Locale as SystemLocale, locale_match};
use ssfmt::Locale as FormatLocale;

pub(crate) fn formatter_locale(locale: SystemLocale) -> FormatLocale {
    let decimal_separator = locale_match!(locale => LC_NUMERIC::DECIMAL_POINT)
        .chars()
        .next()
        .expect("locale data always contains a decimal separator");
    let thousands_separator = locale_match!(locale => LC_NUMERIC::THOUSANDS_SEP)
        .chars()
        .next()
        .unwrap_or(',');
    let am_pm = locale_match!(locale => LC_TIME::AM_PM);
    FormatLocale {
        decimal_separator,
        thousands_separator,
        currency_symbol: locale_match!(locale => LC_MONETARY::CURRENCY_SYMBOL),
        am_string: am_pm[0],
        pm_string: am_pm[1],
        month_names_short: locale_array(locale_match!(locale => LC_TIME::ABMON)),
        month_names_full: locale_array(locale_match!(locale => LC_TIME::MON)),
        day_names_short: locale_array(locale_match!(locale => LC_TIME::ABDAY)),
        day_names_full: locale_array(locale_match!(locale => LC_TIME::DAY)),
    }
}

fn locale_array<const LENGTH: usize>(values: &'static [&'static str]) -> [&'static str; LENGTH] {
    std::array::from_fn(|index| values[index])
}
