//! Mirrors the `ExcelRow` interface generated by `#[derive(ExcelRow)]`.

use crate::analysis_context::Result;
use crate::converter_registry::ConverterRegistry;
use crate::excel_column::ExcelColumn;
use crate::excel_write_metadata::ExcelWriteMetadata;
use crate::row_data::RowData;

/// Compile-time mapping implemented by `#[derive(ExcelRow)]`.
///
/// Java exposes the same five entry points on the
/// `com.alibaba.excel.metadata.ModelBuildEventListener` /
/// `AbstractHolder` runtime reflection path. Rust moves all five to the
/// `ExcelRow` trait so the [`easyexcel-derive`] macro can generate the impl
/// at compile time.
pub trait ExcelRow: Sized {
    /// Returns static column metadata. (Java `ExcelHeadProperty.getHeadMap().values()`)
    fn schema() -> &'static [ExcelColumn];

    /// Returns annotation-driven dimensions used by writers. (Java
    /// `ExcelWriteHeadProperty`)
    #[must_use]
    fn write_metadata() -> &'static ExcelWriteMetadata {
        const METADATA: ExcelWriteMetadata = ExcelWriteMetadata::new();
        &METADATA
    }

    /// Converts a physical row into the user type. (Java `ModelBuildEventListener.buildUserModel`)
    ///
    /// # Errors
    ///
    /// Returns a location-aware conversion error when any field cannot be decoded.
    fn from_row(row: &RowData) -> Result<Self>;

    /// Converts a physical row using Java-style globally registered converters.
    /// (Java `ModelBuildEventListener` with `ConverterRegistry`)
    ///
    /// # Errors
    ///
    /// Returns a location-aware conversion error.
    fn from_row_with_converters(row: &RowData, _converters: &ConverterRegistry) -> Result<Self> {
        Self::from_row(row)
    }

    /// Converts the user type into schema-ordered cells.
    ///
    /// # Errors
    ///
    /// Returns an error when any field cannot be encoded as an Excel cell.
    fn to_row(&self) -> Result<Vec<crate::cell_value::CellValue>>;

    /// Converts the value using Java-style globally registered converters.
    ///
    /// # Errors
    ///
    /// Returns an error when a field cannot be represented as an Excel cell.
    fn to_row_with_converters(
        &self,
        _converters: &ConverterRegistry,
    ) -> Result<Vec<crate::cell_value::CellValue>> {
        self.to_row()
    }
}
