//! Rust counterpart of Java `com.alibaba.excel.util.BeanMapUtils`.
//!
//! Java generates a CGLIB `BeanMap` at runtime. Rust uses the compile-time
//! [`crate::ExcelRow`] contract and materializes the same field-name lookup
//! without reflection or generated bytecode.

use std::collections::BTreeMap;

use crate::{CellValue, ConverterRegistry, ExcelError, ExcelRow};

/// Field-name view of an [`ExcelRow`].
///
/// Values are the converted write values used by the actual writer pipeline.
/// Declared Rust field types are retained separately for converter and template
/// code that needs Java `BeanMap.getPropertyType`-equivalent metadata.
#[derive(Debug, Clone, PartialEq)]
pub struct BeanMap {
    values: BTreeMap<&'static str, CellValue>,
    field_types: BTreeMap<&'static str, Option<&'static str>>,
}

impl BeanMap {
    /// Returns the value associated with a Rust field name.
    #[must_use]
    pub fn get(&self, field_name: &str) -> Option<&CellValue> {
        self.values.get(field_name)
    }

    /// Returns the declared Rust type for a field.
    ///
    /// Mirrors Java `BeanMap.getPropertyType`; manually implemented
    /// [`ExcelRow`] schemas may legitimately return `None`.
    #[must_use]
    pub fn property_type(&self, field_name: &str) -> Option<&'static str> {
        self.field_types.get(field_name).copied().flatten()
    }

    /// Iterates values in deterministic field-name order.
    pub fn iter(&self) -> impl Iterator<Item = (&'static str, &CellValue)> {
        self.values.iter().map(|(field, value)| (*field, value))
    }

    /// Returns the number of mapped fields.
    #[must_use]
    pub fn len(&self) -> usize {
        self.values.len()
    }

    /// Returns whether no fields were mapped.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.values.is_empty()
    }
}

/// Creates a field-name map from an [`ExcelRow`].
///
/// This is the Rust equivalent of `BeanMapUtils.create(bean)` for write and
/// template-fill paths. It executes the same `ExcelRow::to_row` conversion used
/// by production writers instead of returning a type-erased placeholder.
///
/// # Errors
///
/// Returns a conversion error from [`ExcelRow::to_row`], or a format error if a
/// custom implementation returns a different value count than its schema.
pub fn create<T: ExcelRow>(bean: &T) -> Result<BeanMap, ExcelError> {
    create_with_converters(bean, &ConverterRegistry::default())
}

/// Creates a field-name map using an explicit converter registry.
///
/// # Errors
///
/// Returns a conversion error or a schema/value cardinality mismatch.
pub fn create_with_converters<T: ExcelRow>(
    bean: &T,
    converters: &ConverterRegistry,
) -> Result<BeanMap, ExcelError> {
    let schema = T::schema();
    let values = bean.to_row_with_converters(converters)?;
    if values.len() != schema.len() {
        return Err(ExcelError::Format(format!(
            "ExcelRow schema/value length mismatch: schema={}, values={}",
            schema.len(),
            values.len()
        )));
    }
    Ok(BeanMap {
        values: schema
            .iter()
            .zip(values)
            .map(|(column, value)| (column.field, value))
            .collect(),
        field_types: schema
            .iter()
            .map(|column| (column.field, column.field_type))
            .collect(),
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{ExcelColumn, ExcelWriteMetadata, RowData};

    struct UserRow {
        name: String,
        age: i64,
    }

    impl ExcelRow for UserRow {
        fn schema() -> &'static [ExcelColumn] {
            const COLUMNS: &[ExcelColumn] = &[
                ExcelColumn::new("name", "Name", Some(0), 0, None).with_field_type("String"),
                ExcelColumn::new("age", "Age", Some(1), 1, None).with_field_type("i64"),
            ];
            COLUMNS
        }

        fn write_metadata() -> &'static ExcelWriteMetadata {
            const METADATA: ExcelWriteMetadata = ExcelWriteMetadata::new();
            &METADATA
        }

        fn from_row(_row: &RowData) -> crate::Result<Self> {
            unreachable!("bean map test only exercises write conversion")
        }

        fn to_row(&self) -> crate::Result<Vec<CellValue>> {
            Ok(vec![
                CellValue::String(self.name.clone()),
                CellValue::Int(self.age),
            ])
        }
    }

    #[test]
    fn create_maps_real_excel_row_values_and_declared_types() {
        let map = create(&UserRow {
            name: "Alice".to_owned(),
            age: 18,
        })
        .expect("bean map");

        assert_eq!(
            map.get("name"),
            Some(&CellValue::String("Alice".to_owned()))
        );
        assert_eq!(map.get("age"), Some(&CellValue::Int(18)));
        assert_eq!(map.property_type("name"), Some("String"));
        assert_eq!(map.property_type("age"), Some("i64"));
        assert_eq!(map.len(), 2);
    }

    struct InvalidRow;

    impl ExcelRow for InvalidRow {
        fn schema() -> &'static [ExcelColumn] {
            const COLUMNS: &[ExcelColumn] = &[ExcelColumn::new("value", "Value", Some(0), 0, None)];
            COLUMNS
        }

        fn from_row(_row: &RowData) -> crate::Result<Self> {
            Ok(Self)
        }

        fn to_row(&self) -> crate::Result<Vec<CellValue>> {
            Ok(Vec::new())
        }
    }

    #[test]
    fn create_rejects_schema_value_mismatch_instead_of_silently_dropping_fields() {
        let error = create(&InvalidRow).expect_err("mismatch must fail");
        assert!(error.to_string().contains("schema/value length mismatch"));
    }
}
