//! Mirrors Java com.alibaba.excel.util.ClassUtils.
//!
//! Java relies on reflection (`java.lang.Class.getDeclaredFields`,
//! `Field.setAccessible`) to map POJO fields to Excel columns. The Rust
//! port replaces reflection with the `easyexcel_macro::ExcelRow` macro,
//! which generates the equivalent metadata at compile time. These
//! functions are kept as 1:1 placeholders so that callers ported from the
//! Java codebase have an obvious anchor to migrate to.

#![allow(dead_code)]

use std::any::TypeId;

use crate::excel_error::ExcelError;

/// Mirrors `com.alibaba.excel.util.ClassUtils#declaredExcelContentProperty`.
///
/// Returns `None` because field metadata is generated by the
/// `#[derive(ExcelRow)]` macro rather than runtime reflection.
#[must_use]
pub fn declared_excel_content_property(_type_id: TypeId) -> Option<()> {
    None
}

/// Mirrors `com.alibaba.excel.util.ClassUtils#combineExcelContentProperty`.
pub fn combine_excel_content_property() -> Result<(), ExcelError> {
    Ok(())
}

/// Mirrors `com.alibaba.excel.util.ClassUtils#declaredFields`.
///
/// In Rust the field list is provided by `derive(ExcelRow)`; this helper
/// returns an empty slice as a placeholder.
#[must_use]
pub fn declared_fields(_type_id: TypeId) -> &'static [&'static str] {
    &[]
}

/// Mirrors `com.alibaba.excel.util.ClassUtils#removeThreadLocalCache`.
///
/// Java caches reflected `Field` arrays in a `ThreadLocal` for performance.
/// Rust field info is compile-time (`&'static [ExcelColumn]`), no runtime
/// cache needed. The counter allows callers to verify the clear lifecycle.
pub fn remove_thread_local_cache() {
    use std::sync::atomic::{AtomicU32, Ordering};
    static CLEAR_COUNT: AtomicU32 = AtomicU32::new(0);
    CLEAR_COUNT.fetch_add(1, Ordering::Relaxed);
}
